#   A basic travis.yml boilerplate for Django projects

language: python

python:
  - 3.6

install: pip install --user -r requirements.txt

env:
  - DJANGO=2.0.4

before_install:
  - export DJANGO_SETTINGS_MODULE=bebeemaps.settings
  - export PYTHONPATH=$HOME/builds/tadanmf/https://github.com/bebees/BebeesMaps.git
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - tadanmf@gmail.com